### ISSUE TITLE
Semiphemeral.com 500 Internal Server Error

### ISSUE THREAD

**Issue by nunesgh** [micahflee/semiphemeral#76] opened 2021-03-06 13:57 UTC
Hi there,

I've been experiencing several issues with [semiphemeral.com](semiphemeral.com). Currently I cannot add new tweets to the exception list neither delete my account and start over. In both cases, the browser console throws a `500 Internal Server Error`.

After confirming the account deletion, I get redirected to [semiphemeral.com](semiphemeral.com) landing page, the following is logged on the console, and the account is not deleted:
```
Error fetching user TypeError: NetworkError when attempting to fetch resource. Settings.vue:302:19
XHRPOSThttps://semiphemeral.com/api/settings/delete_account
[HTTP/1.1 500 Internal Server Error 190ms]
```

If I go to the tweets tab, several messages are logged on the console, including:
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 3 utils.js:35:9

Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools vue.runtime.esm.js:8418:47

You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html vue.runtime.esm.js:8428:45

Error: FeatureSwitchContext was not correctly initialized
    u https://platform.twitter.com/embed/embed.vendors~loaders.video.VideoPlayerDefaultUI.984b17e08ee65ce1addb.js:1
    value https://platform.twitter.com/embed/embed.vendors~loaders.video.VideoPlayerDefaultUI.984b17e08ee65ce1addb.js:1
    n https://platform.twitter.com/embed/embed.vendors~loaders.video.VideoPlayerDefaultUI.984b17e08ee65ce1addb.js:1
    mu https://platform.twitter.com/embed/embed.modules.abd697ba7053cef5bdb1.js:51
    cs https://platform.twitter.com/embed/embed.modules.abd697ba7053cef5bdb1.js:51
    us https://platform.twitter.com/embed/embed.modules.abd697ba7053cef5bdb1.js:51
    Ju https://platform.twitter.com/embed/embed.modules.abd697ba7053cef5bdb1.js:51
    Gi https://platform.twitter.com/embed/embed.modules.abd697ba7053cef5bdb1.js:51
    unstable_runWithPriority https://platform.twitter.com/embed/embed.modules.abd697ba7053cef5bdb1.js:59
    Hi https://platform.twitter.com/embed/embed.modules.abd697ba7053cef5bdb1.js:51
    Gi https://platform.twitter.com/embed/embed.modules.abd697ba7053cef5bdb1.js:51
    F https://platform.twitter.com/embed/embed.modules.abd697ba7053cef5bdb1.js:59
    onmessage https://platform.twitter.com/embed/embed.modules.abd697ba7053cef5bdb1.js:59
    EventHandlerNonNull* https://platform.twitter.com/embed/embed.modules.abd697ba7053cef5bdb1.js:59
    s https://platform.twitter.com/embed/embed.runtime.ebbf169906077e22e5f1.js:1
    <anonymous> https://platform.twitter.com/embed/embed.modules.abd697ba7053cef5bdb1.js:51
    s https://platform.twitter.com/embed/embed.runtime.ebbf169906077e22e5f1.js:1
    <anonymous> https://platform.twitter.com/embed/embed.modules.abd697ba7053cef5bdb1.js:51
    s https://platform.twitter.com/embed/embed.runtime.ebbf169906077e22e5f1.js:1
    <anonymous> https://platform.twitter.com/embed/embed.modules.abd697ba7053cef5bdb1.js:10
    s https://platform.twitter.com/embed/embed.runtime.ebbf169906077e22e5f1.js:1
    99 https://platform.twitter.com/embed/embed.Tweet.efb4bb7234b7cc7ce8c1.js:1
    s https://platform.twitter.com/embed/embed.runtime.ebbf169906077e22e5f1.js:1
    266 https://platform.twitter.com/embed/embed.Tweet.efb4bb7234b7cc7ce8c1.js:1
    s https://platform.twitter.com/embed/embed.runtime.ebbf169906077e22e5f1.js:1
    d https://platform.twitter.com/embed/embed.runtime.ebbf169906077e22e5f1.js:1
    n https://platform.twitter.com/embed/embed.runtime.ebbf169906077e22e5f1.js:1
    <anonymous> https://platform.twitter.com/embed/embed.Tweet.efb4bb7234b7cc7ce8c1.js:1
 undefined embed.modules.abd697ba7053cef5bdb1.js:10:59403
```
At least two other `Error: FeatureSwitchContext was not correctly initialized` also appear with the same URL for the first three lines (u, value, n).

Finally, if I click on any checkbox to add a tweet to the exclusion list, the following is logged to the console and I find the checkbox is unchecked after reloading the page:
```
XHRPOSThttps://semiphemeral.com/api/tweets
[HTTP/1.1 500 Internal Server Error 152ms]
```

The only settings that are currently being saved in my account upon change are those for defining the conditions for tweets, retweets, and likes deletion. This has been going on like this since around the first week of February. I hope those console logs are helpful to sort this out.

Thank you in advance.

**Comment by nunesgh** [comment] 2021-03-10 20:41
The same error appeared when using the open source version:
```
[2021-03-10 17:37:15,517] ERROR in app: Exception on /api/statistics [GET]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/.local/lib/python3.8/site-packages/semiphemeral/web.py", line 143, in api_statistics
    return jsonify(common.get_stats())
  File "/home/user/.local/lib/python3.8/site-packages/semiphemeral/common.py", line 28, in get_stats
    int(self.settings.get("user_id"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
127.0.0.1 - - [10/Mar/2021 17:37:15] "GET /api/statistics HTTP/1.1" 500 -
```

**Comment by rtrive** [comment] 2021-11-07 13:56
same to me. I'm trying to configure it for the first time but every time that i saved setting this error happens

**Comment by andrewwippler** [comment] 2021-11-11 16:06
This is a duplicate of #84. Can confirm downgrading to tweepy 3.10.0 works:

`pip install tweepy==3.10.10`

**Comment by kees** [comment] 2021-11-29 19:40
Yeah, dup. Thanks!

**Closed by kees** 2021-11-29 19:40 UTC
