### ISSUE TITLE
Not deleting all old tweets — and I am not sure why!

### ISSUE THREAD

**Issue by neilzone** [micahflee/semiphemeral#41] opened 2019-11-20 19:57 UTC
I have been using semiphemeral for a while, and while it is amazing at deleting recent old tweets, it seems that all tweets older than 265 days are left untouched. semiphemeral is set to delete tweets after 7 days.

For example: https://twitter.com/neil_neilzone/status/1101005301376057345 (this is the newest of the old, should-be-deleted, tweets).

It's possible that I've been running semiphemeral for about 265 days, and so perhaps this, and older, tweets were missed from the initial deletion run.

Is there any way I can force semiphemeral to delete my legacy tweets? Perhaps a config option I'm missing?

**Comment by ssbeltran** [comment] 2019-12-01 18:40
Same issue since several months ago, tweets older than April 2017 won't delete.

**Comment by polariscopio** [comment] 2020-05-10 00:24
Any news about this?

**Comment by micahflee** [comment] 2020-07-23 03:24
Duplicate of #12

**Closed by micahflee** 2020-07-23 03:24 UTC
Labels: duplicate
