### ISSUE TITLE
Only Retrieving New Tweets

### ISSUE THREAD

**Issue by MatthewReinbold** [micahflee/semiphemeral#12] opened 2019-06-07 14:20 UTC
When I first ran the fetch command, it went out and downloaded my tweets until it ran into the rate limit, after which it paused. Watching the datetimes, tweets clear back to 2007 were being referenced (I had 31.4k when attempting to run it). 

However, the localhost browser interface says I only have 1,754 tweets and 1,280 retweets. 

When I ran the delete, it appeared to only delete ~ 210 that were older than my criteria (older than a year, x number of my likes, etc) but everything listed was from the first part of 2018, and nothing older. 

I thought, with those 210 cleared, maybe I needed to re-run fetch as I maybe had some 'headroom' in my rate limit. However, fetch is now only retrieving "most recent" tweets. 

Why are the ancient (and, arguably, the most problematic) tweets not appearing? And how do I get fetch to pull them in so that I can subsequently delete them?

**Comment by micahflee** [comment] 2019-06-09 19:14
Sorry about that. It succeeded in fetching all of my old tweets. I had so many tweets that I hit rate limits multiple times, but each time it just continued where it left off when it was done paising. But here's something you can try.

Your `~/.semiphemeral/settings.json` file contains a field `since_id` which is the tweet id if the most recent tweet that's fetched. This way subsequent runs of fetch won't download tweets that you've already fetched. You can replace whatever that id is with `None` and then re-run fetch, and it should attempt to fetch everything from the beginning again.

Maybe I should add a command line option to force fetching everything again.

**Comment by MatthewReinbold** [comment] 2019-06-09 20:57
Thanks for replying; I'll give this a try tomorrow as I think I've hit my rate limit for today.

**Comment by MatthewReinbold** [comment] 2019-06-10 14:22
Still seeing the same behavior. For reference, to reset the last run, enter `Null`, rather than `None` entered above. 

When I reset the `since_id` by either replacing the value with `Null` or the Id of an older tweet (for example, something from 2010), running fetch seems to start with the latest tweet and outputs 'skipped YYYY-MM-DD ....' going chronologically backwards. It appears to end sometime around April, 2018 (guessing this is less about the date, but something about the number of calls made). No tweet made from before this time appears in the Semiphemeral tweets UI to allow for selection for exclusion, or is subsequently processed as part of running `semiphemeral delete`.

**Comment by MatthewReinbold** [comment] 2019-06-10 14:44
Did some more spelunking by running queries directly against the SQLite DB. It appears that likes and retweets were completely downloaded and saved, going back to 2007. When I look at tweets that I've sent, however, the entries in the db goes back to July 2012 (which, is odd - it is neither the complete tweet record nor the limited number of items I can see through the semiphemeral UI). 

```
select * from tweets 
where user_id = *[twitter_user_id]*
and is_deleted = 0 
and exclude_from_delete = 0 
order by created_at ASC 
limit 25
```

**Comment by MatthewReinbold** [comment] 2019-06-12 12:45
Waited a day to ensure that there wasn't an API rate limit problem. Reset the "since_id" to null, and reran 'semiphemeral fetch'. Scrolling through the output, it started by grabbing the latest, greatest, and then skipped tweets (because they were already downloaded) going back to April, 2018. It then stopped and started grabbing retweets and likes. 

~~~
...
Skipped 2018-04-11 @libel_vox, id=983917910195306496
Skipped 2018-04-10 @libel_vox, id=983841915702595584
Skipped 2018-04-10 @libel_vox, id=983675390249046016
Skipped 2018-04-10 @libel_vox, id=983672970953543680
Skipped 2018-04-06 @libel_vox, id=982273202381438976
Fetching tweets that you liked
Fetched 2019-06-12 @KevlinHenney, id=1138717554602631168
Fetched 2019-06-11 @jimmykimmel, id=1138499274130411520
...
~~~

**Comment by russss** [comment] 2019-06-24 15:56
I hit this too, because I cancelled the initial fetch to move it to another machine.

Would it be possible to save the oldest fetched tweet ID in the config, and then try fetching everything older than that (as well as everything newer than `since_id`) when the fetch command is run? I think that would be a neater solution than having a command line option.

**Comment by bffcorianne** [comment] 2019-08-08 20:27
@MatthewReinbold did manually resetting the oldest fetched tweet id in config and refetching work for you? my initial fetch got cancelled my accident, is that the cause? I can't capture all my tweets. @russss like you, a query on the SQLite db returns an arbitrary date in 2015, but the delete only went back to late 2017.

**Comment by r4v5** [comment] 2019-08-24 15:08
I completely wiped my database and configuration, as someone who thought the ^C I did was ruining things, and it seems that what's actually happening is the API responses for my user_timeline just stop back in 2017. Search of `(from:userid) until:datetime` still return tweets, though, and querying the api for a specific tweet seems to work.

It seems like the options for handling this are either
1) importing old tweets from user exports like in #23, or
2) doing twitter searches, which as far as I can tell requires paid access for the [fulltext api](https://developer.twitter.com/en/docs/tweets/search/overview/premium)

**Comment by kees** [comment] 2021-12-10 17:10
With #23 merged, I think this bug can be closed. Please reopen if not! :)

**Closed by kees** 2021-12-10 17:10 UTC
