### ISSUE TITLE
500 Internal Server Error with the self-hosted version while running configure

### ISSUE THREAD

**Issue by shivangswain** [micahflee/semiphemeral#94] opened 2021-12-13 15:40 UTC
Note: I have already used both the latest version of Tweepy and Tweepy v3.10.0.

`⋊> ~ semiphemeral configure`
```
semiphemeral 0.7
Load this website in a browser to configure semiphemeral, and press Ctrl-C when done
http://127.0.0.1:8080

 * Serving Flask app 'semiphemeral.web' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [13/Dec/2021 21:05:55] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [13/Dec/2021 21:05:55] "GET /settings HTTP/1.1" 200 -
127.0.0.1 - - [13/Dec/2021 21:05:55] "GET /static/style.css HTTP/1.1" 200 -
127.0.0.1 - - [13/Dec/2021 21:05:55] "GET /static/js/lib/jquery-3.4.1.min.js HTTP/1.1" 200 -
127.0.0.1 - - [13/Dec/2021 21:05:55] "GET /static/js/base.js HTTP/1.1" 200 -
127.0.0.1 - - [13/Dec/2021 21:05:55] "GET /static/js/settings.js HTTP/1.1" 200 -
127.0.0.1 - - [13/Dec/2021 21:05:55] "GET /api/statistics HTTP/1.1" 200 -
127.0.0.1 - - [13/Dec/2021 21:05:58] "GET /api/statistics HTTP/1.1" 200 -
[2021-12-13 21:08:21,473] ERROR in app: Exception on /settings [POST]
Traceback (most recent call last):
  File "/home/shivangswain/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shivangswain/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shivangswain/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shivangswain/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/shivangswain/.local/lib/python3.9/site-packages/semiphemeral/web.py", line 106, in edit_settings
    twitter = Twitter(common)
  File "/home/shivangswain/.local/lib/python3.9/site-packages/semiphemeral/twitter.py", line 40, in __init__
    user = self.api.get_user(self.common.settings.get("username"))
  File "/home/shivangswain/.local/lib/python3.9/site-packages/tweepy/binder.py", line 253, in _call
    return method.execute()
  File "/home/shivangswain/.local/lib/python3.9/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'message': 'You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve', 'code': 453}]
127.0.0.1 - - [13/Dec/2021 21:08:21] "POST /settings HTTP/1.1" 500 -
```

`⋊> ~ lsb_release -a`
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

**Comment by Flash1232** [comment] 2021-12-27 17:38
Same here. They force new regular developer accounts to use Twitter API v2, and accessing Twitter API v1.1 now requires a higher account tier.
https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#Access

"If you were approved for a developer account before November 15th, 2021, will were (you were?) automatically converted to Elevated access."

Semiphemeral is using Tweepy 3.10 which was made for Twitter API v1.1:
https://github.com/tweepy/tweepy/blob/29df541c1f72dee6b2ee7a9d71e21e90f7634b13/tweepy/api.py#L22

So anyone that only created an account after that date won't be able to use Semiphemeral unless going for an ads API application. The repo will have to upgrade to Tweepy v4 to attract new users.

**Comment by slash9492** [comment] 2022-01-03 16:31
Same issue, running it on **MacOS 12.1**
I just got my developer account so, this might be the same scenario.


❯ semiphemeral configure                                                      ~
semiphemeral 0.7
Load this website in a browser to configure semiphemeral, and press Ctrl-C when done
http://127.0.0.1:8080

 * Serving Flask app 'semiphemeral.web' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [03/Jan/2022 11:06:15] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [03/Jan/2022 11:06:15] "GET /settings HTTP/1.1" 200 -
127.0.0.1 - - [03/Jan/2022 11:06:16] "GET /static/style.css HTTP/1.1" 200 -
127.0.0.1 - - [03/Jan/2022 11:06:16] "GET /static/js/lib/jquery-3.4.1.min.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Jan/2022 11:06:16] "GET /static/js/base.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Jan/2022 11:06:16] "GET /static/js/settings.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Jan/2022 11:06:16] "GET /api/statistics HTTP/1.1" 200 -
127.0.0.1 - - [03/Jan/2022 11:06:16] "GET /favicon.ico HTTP/1.1" 404 -
[2022-01-03 11:11:51,146] ERROR in app: Exception on /settings [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/semiphemeral/web.py", line 106, in edit_settings
    twitter = Twitter(common)
  File "/usr/local/lib/python3.9/site-packages/semiphemeral/twitter.py", line 33, in __init__
    self.api = tweepy.API(
TypeError: __init__() got an unexpected keyword argument 'wait_on_rate_limit_notify'
127.0.0.1 - - [03/Jan/2022 11:11:51] "POST /settings HTTP/1.1" 500 -

**Comment by kees** [comment] 2022-01-23 18:05
Ugh. Forcing new users into the new API makes sense, but is pretty annoying for clients.

This bug is basically a duplicate of issue #92

**Comment by bonjour81** [comment] 2023-04-11 07:54
Same issue here, is the online version also concerned ? at least I have the same Error 500 message

**Closed** 2023-08-01 17:08 UTC
