### ISSUE TITLE
Unable to delete old tweets

### ISSUE THREAD

**Issue by apc005** [micahflee/semiphemeral#54] opened 2020-07-15 13:41 UTC
Hi
I sucesfully installed semiphemeral. I configured it to delete tweets older than 90 days but nothing happened. I was able to delete some tweets by setting the limit to 10 days (but its too short) but the oldest tweets remained...

I have around 30k tweets to delete and really don't understant what I'm doing wrong.

Thanks

**Comment by micahflee** [comment] 2020-07-23 03:23
Duplicate of #12

**Closed by micahflee** 2020-07-23 03:23 UTC
Labels: duplicate
