### ISSUE TITLE
version error when running pip3 install semiphemeral

### ISSUE THREAD

**Issue by fynnit** [micahflee/semiphemeral#33] opened 2019-07-31 21:16 UTC
I get this error after trying to install semiphemeral:

`Could not fetch URL https://pypi.python.org/simple/semiphemeral/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping

Could not find a version that satisfies the requirement semiphemeral (from versions: )
No matching distribution found for semiphemeral`

any help?

**Comment by kees** [comment] 2021-11-29 20:55
This sounds like a local certificate authority issue, or a remote TLS problem. I can't reproduce this, so I'm closing it for now.

**Closed by kees** 2021-11-29 20:55 UTC
